[package]
name = "jaeger-out-of-order"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opentelemetry-jaeger = "0.16.0"
opentelemetry = "0.17.0"
futures-executor = "0.3.21"